eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: index-config-server

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/KaguyaShinomiya/trendConfig
          search-paths: respo
