
spring:
  application:
    name: trend-trading-backtest-view
  zipkin:
    base-url: http://localhost:9411

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"